### PR TITLE
feat: migrate to modular Firebase 9 & @angular/fire 7

### LINKED ISSUE #41: Firebase V9/AngularFire V7.0.4
After updating to Angularfire V7 / firebase V9 i receive the following error on compile

```
Error: Failed to compile entry-point @ngxs-labs/firestore-plugin (`es2015` as esm2015) due to compilation errors:
node_modules/@ngxs-labs/firestore-plugin/fesm2015/ngxs-labs-firestore-plugin.js:113:26 - error NG1010: Value at position 2 in the NgModule.imports of NgxsFirestor
eModule is not a reference
  Value could not be determined statically.

113                 imports: [CommonModule, NgxsModule.forFeature([NgxsFirestoreState]), AngularFirestoreModule]
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@ngxs-labs/firestore-plugin/fesm2015/ngxs-labs-firestore-plugin.js:113:86
    113                 imports: [CommonModule, NgxsModule.forFeature([NgxsFirestoreState]), AngularFirestoreModule]
                                                                                             ~~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.


Compiling @ngxs-labs/firestore-plugin : es2015 as esm2015
C:\app\node_modules\@angular\compiler-cli\ngcc\src\execution\tasks\completion.js:57
            throw new Error(createErrorMessage(fs, task, message));
            ^

Error: Failed to compile entry-point @ngxs-labs/firestore-plugin (`es2015` as esm2015) due to compilation errors:
node_modules/@ngxs-labs/firestore-plugin/fesm2015/ngxs-labs-firestore-plugin.js:113:26 - error NG1010: Value at position 2 in the NgModule.imports of NgxsFirestor
eModule is not a reference
  Value could not be determined statically.

113                 imports: [CommonModule, NgxsModule.forFeature([NgxsFirestoreState]), AngularFirestoreModule]
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  node_modules/@ngxs-labs/firestore-plugin/fesm2015/ngxs-labs-firestore-plugin.js:113:86
    113                 imports: [CommonModule, NgxsModule.forFeature([NgxsFirestoreState]), AngularFirestoreModule]
                                                                                             ~~~~~~~~~~~~~~~~~~~~~~
    Unknown reference.
```

### PR DESCRIPTION
**Pull request by Krismix1**
Migrate to Firebase 9 modular design & @angular/fire 7 (fixes #41).

I have migrated to the new modular API from Firebase. This means that the library consumers will also have to migrate to this. Do you think it needs to add a compatibility layer?

Enable Ivy compilation (though maybe it could be disabled) and use partial-Ivy mode as recommended in the [docs](https://v12.angular.io/guide/creating-libraries#ensuring-library-version-compatibility).

I have tried to keep the number of changes in the API to a minimum. However, I had to add explicit generics as otherwise it was inferred as `DocumentData` (maybe it could be undone and just fixed with explicit casting).

Other problems are that `QueryFn` and `GetOptions` are no longer available, so temporarily define them in the library.

TODO:
- Update README with new modular design
- Update changelog
- Update package version?
- Perhaps add small migration instructions?

### CODE REVIEW

**Comment by Krismix1** [comment]
@joaqcid could I maybe get some opinions about the remarks/issues I wrote in the PR description or if you agree to the PR changes?

**Comment by joaqcid** [comment]
@Krismix1 thank you very much for this PR, looks good, i've already released v1.0.0 compatible with latest firebase and @angular/fire, 

nonetheless i'll take a look to this PR and see if we can use the modular approach in the library, thank you!

**Comment by sroettering** [comment]
It would be nice to merge this PR if it removes usages of the angular fire compat stuff. I upgraded my app today to angular 14, firebase 9 and @angular/fire 7 but I get compilation errors that only occur when loading the NgxsFirestoreModule.
This is the error I'm getting:

image

**Comment by joaqcid** [comment]
hi @sroettering check downgrading to @ngxs/store v3.7.2, i've seen that error with 3.7.4

**Comment by sroettering** [comment]
@joaqcid Thanks that helped!
But nonetheless it would be nice to get rid of the non-treeshakeable parts of firebase :)

**Comment by Krismix1** [comment]
Agree regarding treeshake support :)
I've merged the latest master into my branch.

**Comment by mcz-xiocku** [comment]
Any news on this PR :) ?

**Comment by joaqcid** [comment]
hi @mcz-xiocku ill try to look at this, and possibly release a version with the modular firebase option

**Comment by SGoldenGraham** [comment]
@joaqcid Any chance you may be able to look into reviewing and merging this? We are blocked upgrading to the latest firebase release until this is completed. We are going to pull and test the PR to make sure it works as well.

**Comment by joaqcid** [comment]
hi all 

i made a couple of changes to this PR and merged as v1.1.0

thanks @Krismix1 for this code, i used pretty much all of it!

for v2.0.0 im planning to extract `NgxsFirestore` and 'NgxsFirestorePageService' to its own package to be able to adjust to Firebase changes more quickly and avoid dependency of the plugin wiht any Firebase version

**Pull request closed without merging**
