### PR TITLE
feat: include mapTo, mapFrom, idField options

### PR DESCRIPTION
**Pull request by joaqcid**

### CODE REVIEW

**Comment by joaqcid** [comment]
@markwhitfeld what do you think?

**Comment by markwhitfeld** [comment]
I was thinking that you could just specify a `firestore.FirestoreDataConverter` and then this would be used on the doc/collection ref:
see ref API for `.withConverter(this.converter)`.

**Comment by joaqcid** [comment]
> I was thinking that you could just specify a `firestore.FirestoreDataConverter` and then this would be used on the doc/collection ref:
> see ref API for `.withConverter(this.converter)`.

It looks like there's no option to use `withConverter` when querying a specific doc...

**Comment by joaqcid** [comment]
@markwhitfeld implemeted `firebase.firestore.FirestoreDataConverter` what do you think now?

**Pull request closed without merging**
